# Generated by Django 3.1.2 on 2022-04-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('stress_level', models.FloatField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Scan Images',
                'ordering': ['-id'],
            },
        ),
    ]
