# Generated by Django 3.1.2 on 2022-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_scanimage_stress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
